apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kuma.io/sidecar-injection: enabled
  name: katt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katt
  name: katt
  namespace: katt
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: katt
  selector:
    app: katt
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katt-debug
  name: katt-debug
  namespace: katt
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: katt-debug
  selector:
    app: katt
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katt-home
  name: katt-home
  namespace: katt
spec:
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: sshd
  selector:
    app: katt-home
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: katt
  name: katt
  namespace: katt
spec:
  selector:
    matchLabels:
      app: katt
  template:
    metadata:
      labels:
        app: katt
    spec:
      containers:
      - image: katt-image
        name: katt
        ports:
        - containerPort: 8000
          name: katt
        - containerPort: 5555
          name: katt-debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: katt-home
  name: katt-home
  namespace: katt
spec:
  selector:
    matchLabels:
      app: katt-home
  template:
    metadata:
      labels:
        app: katt-home
    spec:
      containers:
      - image: k3d-hub.defn.ooo:5000/defn/home:home
        name: katt-home
        ports:
        - containerPort: 2222
          name: sshd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: katt
  namespace: katt
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`katt.defn.ooo`)
    middlewares:
    - name: traefik-forward-auth
    services:
    - name: katt
      port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: katt-debug
  namespace: katt
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`katt-debug.defn.ooo`)
    services:
    - name: katt-debug
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: katt
spec:
  forwardAuth:
    address: http://traefik-forward-auth.traefik.svc.cluster.local:4181
    authResponseHeaders:
    - X-Forwarded-User
