apiVersion: apps/v1
kind: Deployment
metadata:
  name: katt
  labels:
    app: katt
spec:
  selector:
    matchLabels:
      app: katt
  template:
    metadata:
      labels:
        app: katt
    spec:
      containers:
        - name: katt
          image: k3d-hub.defn.ooo:5000/katt-image
          ports:
            - name: katt
              containerPort: 8000
            - name: katt-debug
              containerPort: 5555
