apiVersion: v1
kind: Namespace
metadata:
  name: katt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katt
  name: katt
  namespace: katt
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: katt
  selector:
    app: katt
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: katt
  name: katt
  namespace: katt
spec:
  selector:
    matchLabels:
      app: katt
  template:
    metadata:
      labels:
        app: katt
    spec:
      containers:
      - image: defn/katt-image
        name: katt
        ports:
        - containerPort: 8000
          name: katt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: katt
  namespace: katt
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`katt.defn.ooo`)
    middlewares:
    - name: traefik-forward-auth
    services:
    - name: katt
      port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: katt
spec:
  forwardAuth:
    address: http://traefik-forward-auth.traefik.svc.cluster.local:4181
    authResponseHeaders:
    - X-Forwarded-User
